# Site settings
title: Albert Kabanda
title_bottom: Albert Kabanda
email: albertkabanda2027@northwestern.edu
#description: Albert Research Group
baseurl: ""
url: "https://albertkabanda.github.io"

# theme: minimal-mistakes-jekyll
# minimal_mistakes_skin: "aqua"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
google_analytics_4: G-JVNKYC0903
# google_tag_manager: XXX

# Footer info
affiliation: >
  <a href="https://deeps.northwestern.edu/"><i class="fa fa-1x"></i> Dept. of Earth, Environmental and Planetary Sciences</a><br/>
  <a href="https://www.northwestern.edu/"><i class="fa fa-1x"></i> Northwestern University</a>

location: >
  Evanston <br/>
  Evanston, IL<br/>

contact: >
  <a href="mailto:albertkabanda2027@northwestern.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Email: albertkabanda2027@northwestern.edu</a> <br/>
  Last updated on Oct 15, 2025
# Pages shown in navbar
nav_pages:
- name: About
  url: /About/
- name: Research
  url: /Research/
- name: Fieldwork
  url: /Fieldwork/
- name: Publications
  url: /Publications/
- name: Talks & Presentations
  url: /Talks/
- name: Supervision
  url: /Supervision/
- name: Teaching
  url: /teaching/
- name: Posts
  url: /Posts/
- name: Cool Stuff
  url: /Cool-Stuff/

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll-scholar

scholar:
  last_name: Kabanda
  first_name: [Albert]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"
    
exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile

